<a href="https://colab.research.google.com/github/Killingjoke1797/Killingjoke1797/blob/main/Misiones_Alterno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Misión 1***

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from scipy.stats import pearsonr, kendalltau, spearmanr

In [ ]:
data = pd.read_csv('dataset_renovables_con_errores.csv')
data

,Planta Energética,Tipo de Energía,Nivel de Democratización Energética,Número de Comunidades Energéticas,Número de Proyectos en Marcha,Capacidad Generada (MW),Reducción de CO2 (toneladas),Región,Costo de Producción ($/MW),Año de Instalación,"Rentabilidad en 10 años (Rentable=1, No Rentable=0)"
0,SolarFlow,Solar,Alto,42,1.0,100.46,48910.59373127165,Sur,1893.656170,2005,1
1,SunWave,Solar,Bajo,12,17.0,NaN,156615.16814130466,Oeste,3398.187477,2015,0
2,EcoWind,NaN,Bajo,47,NaN,52.62,25618.907447138306,Sur,1642.900952,2010,0
3,SolarFlow,Geotérmica,NaN,24,11.0,NaN,381289.3836417021,Este,2796.374954,2010,1
4,HydroFlux,Hidrógeno verde,Medio,37,5.0,404.25,196815.72283363095,Norte,2144.411388,2020,1
...,...,...,...,...,...,...,...,...,...,...,...
995,EcoWind,Hidrógeno verde,Bajo,20,NaN,522.12,254202.65975484328,Norte,2996.979129,2020,1
996,Solaris,Eólica,Medio,23,7.0,NaN,203987.26419996214,Este,2846.525998,2010,1
997,SunWave,Eólica,Bajo,22,NaN,207.35,100951.73810650186,Norte,2896.677042,2005,0
998,VientoVerde,Eólica,Bajo,20,16.0,418.24,NaN,Este,2996.979129,2015,1
999,HydroFlux,Eólica,Medio,12,3.0,@#$,39703.95101319135,Sur,3398.187477,2005,1

In [ ]:
data.describe()

,Número de Proyectos en Marcha,Costo de Producción ($/MW),Año de Instalación,"Rentabilidad en 10 años (Rentable=1, No Rentable=0)"
count,810.000000,1000.000000,1000.000000,1000.00000
mean,10.262963,2620.846302,2012.175000,0.58400
std,5.447467,653.454384,5.605872,0.49314
min,1.000000,1542.598865,2005.000000,0.00000
25%,6.000000,2044.109301,2005.000000,0.00000
50%,10.000000,2620.846302,2010.000000,1.00000
75%,15.000000,3197.583303,2015.000000,1.00000
max,19.000000,3749.244782,2020.000000,1.00000

In [ ]:
data.dtypes

Planta Energética                                       object
Tipo de Energía                                         object
Nivel de Democratización Energética                     object
Número de Comunidades Energéticas                       object
Número de Proyectos en Marcha                          float64
Capacidad Generada (MW)                                 object
Reducción de CO2 (toneladas)                            object
Región                                                  object
Costo de Producción ($/MW)                             float64
Año de Instalación                                       int64
Rentabilidad en 10 años (Rentable=1, No Rentable=0)      int64
dtype: object

Tratamiento para Planta energética

In [ ]:
data['Rentabilidad en 10 años (Rentable=1, No Rentable=0)'].value_counts()

Rentabilidad en 10 años (Rentable=1, No Rentable=0)
1    584
0    416
Name: count, dtype: int64

In [ ]:
#reemplaza los (@#$, error) por valores nulos
data.replace(['@#$', 'error'], np.nan, inplace=True)

In [ ]:
data.isnull().sum() #conteo

Planta Energética                                        5
Tipo de Energía                                         78
Nivel de Democratización Energética                    106
Número de Comunidades Energéticas                        5
Número de Proyectos en Marcha                          190
Capacidad Generada (MW)                                178
Reducción de CO2 (toneladas)                            61
Región                                                  62
Costo de Producción ($/MW)                               0
Año de Instalación                                       0
Rentabilidad en 10 años (Rentable=1, No Rentable=0)      0
dtype: int64

Tratamiento para tipo de energía

In [ ]:
data['Tipo de Energía'].value_counts()

Tipo de Energía
Solar              194
Hidráulica         193
Geotérmica         188
Eólica             188
Hidrógeno verde    159
Name: count, dtype: int64

In [ ]:
data['Número de Comunidades Energéticas'].value_counts()

Número de Comunidades Energéticas
45    30
49    30
21    30
41    29
38    28
15    28
17    28
12    27
8     27
32    26
40    26
27    25
36    24
5     24
23    24
25    23
33    23
22    23
48    23
28    23
31    22
7     22
39    22
42    22
44    22
30    22
26    21
43    21
16    20
34    20
47    20
24    20
10    19
14    19
9     18
13    18
20    17
35    17
29    17
18    16
19    16
46    16
37    16
6     16
11    15
Name: count, dtype: int64

In [ ]:
ntabla = data
media = data['Número de Comunidades Energéticas'].mean()[0]
media

TypeError: can only concatenate str (not "int") to str

In [ ]:
correlacion = data['Número de Comunidades Energéticas', 'Número de Proyectos Renovables', 'Capacidad Generada(MW)','Reducción ']

In [ ]:
moda = ntabla['Tipo de Energía'].mode()[0]
moda
ntabla['Planta Energética'].fillna(moda, inplace = True)
ntabla['Planta Energética'].isnull().sum()

0

In [ ]:
moda = ntabla['Nivel de Democratización Energética'].mode()[0]
moda

ntabla['Nivel de Democratización Energética'].fillna(moda, inplace = True)
ntabla['Nivel de Democratización Energética'].isnull().sum()

'Medio'